name: Test GPT-5 Connection

on:
  workflow_dispatch:

jobs:
  gpt5-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install openai

      - name: Test GPT-5 API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<EOF
          import os
          from openai import OpenAI
          client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
          response = client.chat.completions.create(
              model="gpt-5",
              messages=[{"role": "user", "content": "Say 'Hello DivvyFi!'"}]
          )
          print("✅ GPT-5 response:", response.choices[0].message["content"])
          EOF
