name: Update DivvyFi Site with GPT-5

# When to run the workflow
on:
  workflow_dispatch:    # manual trigger
  schedule:
    - cron: "0 12 * * *" # daily at 12:00 UTC

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install openai

      - name: Run GPT-5 script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/update_index.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update index.html via GPT-5" || echo "No changes to commit"
          git push
